print("this info app:")
name = input("😂what is your name?")
college = input('where is your college?')
principal = input("who is your principal")
print("your details are:")
print("Name", name)
print('Head',principal)
confirm = input('is this ok?')